#!/usr/bin/env bash
# gitlab module — service ops hook: aibox gitlab <action> [args]
# Actions: start | stop | restart | status | logs | credentials
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
. "$DIR/lib.sh"

action="${1:-status}"
[ $# -gt 0 ] && shift
load_env

case "$action" in
start)
  # docker.io source pool: bounded direct probe (healthy → compose pulls direct,
  # zero overhead); direct dead → ranked mirror pre-pull + tag (see lib.sh).
  # shellcheck disable=SC2046
  docker_pool_prepull $(compose_images) || true
  # self-heal: legacy .envs (pre-1.5.0) get the root-password seed before up
  ensure_root_password
  compose up -d "$@"
  port="${GITLAB_HTTP_PORT:-$DEFAULT_HTTP_PORT}"
  timeout_s="${GITLAB_START_TIMEOUT:-600}"
  waited=0
  log "waiting for GitLab to boot (first boot 3-5 min; timeout ${timeout_s}s)..."
  while [ "$waited" -lt "$timeout_s" ]; do
    # readiness gate first (includes the db-migrations checks — the upgrade-hop
    # gate); falls back to sign_in on deploys without the monitoring whitelist
    if http_up_readiness "$port"; then
      ok "GitLab is up: http://127.0.0.1:${port}"
      log "SSH clone  : $(ssh_clone_url)/<group>/<project>.git"
      log "Login      : root — password: aibox gitlab credentials (verified live)"
      exit 0
    fi
    sleep 10
    waited=$((waited + 10))
    if [ $((waited % 60)) -eq 0 ]; then
      state="$(docker inspect -f '{{.State.Health.Status}}' "$CONTAINER_NAME" 2>/dev/null || echo booting)"
      log "  still booting (${waited}s, health: ${state})"
    fi
  done
  warn "GitLab did not answer within ${timeout_s}s — inspect: aibox gitlab logs | docker logs $CONTAINER_NAME"
  exit 1
  ;;
stop)
  compose stop "$@"
  ok "stopped (data volumes untouched)"
  ;;
restart)
  compose restart "$@"
  ok "restarted (the entrypoint re-runs omnibus reconfigure on boot)"
  ;;
# dashboard is an alias of status (merged 2026-09: one "show state" verb —
# operational facts + the rich view; the manager-level aibox dashboard stays separate)
# config: the deploy .env is the store (spec §Configuration).
config)
  load_env
  ROOT="$(deploy_root)"
  CFG_YAML="${DIR}/module.yaml" \
    CFG_STORE="${ROOT}/.env" \
    CFG_APPLY="aibox gitlab restart" \
    cfg_action "$@"
  ;;
status | dashboard)
  compose ps
  port="${GITLAB_HTTP_PORT:-$DEFAULT_HTTP_PORT}"
  if container_running; then
    health="$(docker inspect -f '{{.State.Health.Status}}' "$CONTAINER_NAME" 2>/dev/null || echo none)"
    log "image : $(effective_image)"
    log "health: ${health}"
    if http_up "$port"; then
      ok "UI answers: http://127.0.0.1:${port}"
    else
      warn "UI not answering yet on :${port} (first boot takes 3-5 min)"
    fi
  else
    warn "container ${CONTAINER_NAME} is not running (start: aibox gitlab start)"
  fi
  render_dashboard
  ;;
logs)
  compose logs --tail "${GITLAB_LOG_TAIL:-200}" "$@"
  ;;
credentials)
  # Deterministic: the .env seed (install-generated, never rotated). The old
  # initial_root_password file path is RETIRED — the file's password is
  # regenerated by every reconfigure while the DB keeps the first-seed one
  # (live-caught: the displayed password stopped working on a deploy host).
  # Always verify against the LIVE account — the answer to "is this password
  # correct?" comes from the source of truth, not from a file.
  ensure_root_password
  load_env
  pw="${GITLAB_ROOT_PASSWORD:-}"
  if [ -n "$pw" ]; then
    ok "user    : root"
    ok "password: ${pw}"
    case "$(root_password_verify "${pw}")" in
    true)
      ok "verified: password works on the live root account"
      ;;
    false)
      warn "password INVALID on this instance — volumes were seeded before this password existed (or root was reset)"
      log "reset it: docker exec -it ${CONTAINER_NAME} gitlab-rake \"gitlab:password:reset[root]\""
      ;;
    *)
      warn "could not verify (container down or rails still busy) — retry when up"
      ;;
    esac
  else
    warn "no seeded password (uninstalled? run: aibox install gitlab)"
  fi
  ;;
*)
  die "unknown action: ${action:-} — run: aibox gitlab --help"
  ;;
esac
