#!/usr/bin/env bash
# gitlab module — service ops hook: aibox gitlab <action> [args]
# Actions: start | stop | restart | status | logs | credentials | config
#          | backup | restore | import-secrets   (migration)
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
. "$DIR/lib.sh"

action="${1:-status}"
[ $# -gt 0 ] && shift
load_env

case "$action" in
start)
  # docker.io source pool: bounded direct probe (healthy → compose pulls direct,
  # zero overhead); direct dead → ranked mirror pre-pull + tag (see lib.sh).
  # shellcheck disable=SC2046
  docker_pool_prepull $(compose_images) || true
  # self-heal: legacy .envs (pre-1.5.0) get the root-password seed before up
  ensure_root_password
  # HTTPS is opt-in; a missing cert pair is generated (never overwritten)
  ensure_tls_material
  compose up -d "$@"
  port="${GITLAB_HTTP_PORT:-$DEFAULT_HTTP_PORT}"
  timeout_s="${GITLAB_START_TIMEOUT:-600}"
  waited=0
  log "waiting for GitLab to boot (first boot 3-5 min; timeout ${timeout_s}s)..."
  while [ "$waited" -lt "$timeout_s" ]; do
    # readiness gate first (includes the db-migrations checks — the upgrade-hop
    # gate); falls back to sign_in on deploys without the monitoring whitelist
    if http_up_readiness "$port"; then
      ok "GitLab is up: http://127.0.0.1:${port}"
      log "SSH clone  : $(ssh_clone_url)/<group>/<project>.git"
      log "Login      : root — password: aibox gitlab credentials (the .env seed, verified live)"
      exit 0
    fi
    sleep 10
    waited=$((waited + 10))
    if [ $((waited % 60)) -eq 0 ]; then
      state="$(docker inspect -f '{{.State.Health.Status}}' "$CONTAINER_NAME" 2>/dev/null || echo booting)"
      log "  still booting (${waited}s, health: ${state})"
    fi
  done
  warn "GitLab did not answer within ${timeout_s}s — inspect: aibox gitlab logs | docker logs $CONTAINER_NAME"
  exit 1
  ;;
stop)
  compose stop "$@"
  ok "stopped (data volumes untouched)"
  ;;
restart)
  compose restart "$@"
  ok "restarted (the entrypoint re-runs omnibus reconfigure on boot)"
  ;;
# status is an alias of status (merged 2026-09: one "show state" verb —
# operational facts + the rich view; the manager-level aibox status stays separate)
# config: the deploy .env is the store (spec §Configuration).
config)
  load_env
  ROOT="$(deploy_root)"
  CFG_YAML="${DIR}/module.yaml" \
    CFG_STORE="${ROOT}/.env" \
    CFG_APPLY="aibox gitlab restart" \
    cfg_action "$@"
  ;;
status)
  compose ps
  port="${GITLAB_HTTP_PORT:-$DEFAULT_HTTP_PORT}"
  if container_running; then
    health="$(docker inspect -f '{{.State.Health.Status}}' "$CONTAINER_NAME" 2>/dev/null || echo none)"
    log "image : $(effective_image)"
    log "health: ${health}"
    if http_up "$port"; then
      ok "UI answers: http://127.0.0.1:${port}"
    else
      warn "UI not answering yet on :${port} (first boot takes 3-5 min)"
    fi
  else
    warn "container ${CONTAINER_NAME} is not running (start: aibox gitlab start)"
  fi
  render_status
  ;;
logs)
  compose logs --tail "${GITLAB_LOG_TAIL:-200}" "$@"
  ;;
credentials)
  # Deterministic: the .env seed (install-generated, never rotated). The old
  # initial_root_password file path is RETIRED — the file's password is
  # regenerated by every reconfigure while the DB keeps the first-seed one
  # (live-caught: the displayed password stopped working on a deploy host).
  # Always verify against the LIVE account — the answer to "is this password
  # correct?" comes from the source of truth, not from a file.
  ensure_root_password
  load_env
  pw="${GITLAB_ROOT_PASSWORD:-}"
  if [ -n "$pw" ]; then
    ok "user    : root"
    ok "password: ${pw}"
    log "source    : seeded in the deploy .env (applies at first boot with fresh volumes; GitLab's own random + 24h initial_root_password file is bypassed — the env seed wins)"
    case "$(root_password_verify "${pw}")" in
    true)
      ok "verified: password works on the live root account"
      ;;
    false)
      warn "password INVALID on this instance — volumes were seeded before this password existed (or root was reset)"
      log "reset it: docker exec -it ${CONTAINER_NAME} gitlab-rake \"gitlab:password:reset[root]\""
      ;;
*)
      warn "could not verify (container down or rails still busy) — retry when up"
      ;;
    esac
  else
    warn "no seeded password (uninstalled? run: aibox install gitlab)"
  fi
  ;;
doctor)
  module_doctor "gitlab"
  ;;
    backup)
  # Non-destructive: a GitLab backup inside the running container. It lands in
  # the gitlab_data volume (never in the repo/deploy root) — copy it out with
  # the printed docker cp command.
  container_running || die_code 30 "container is not running (aibox gitlab start)"
  log "creating a GitLab backup inside the container (minutes for a few GB)…"
  printf '%s\n' "yes" | docker exec -i "$CONTAINER_NAME" gitlab-backup create CRON=1 >/dev/null 2>&1 || \
    die "gitlab-backup create failed — run it by hand to see why: docker exec -it $CONTAINER_NAME gitlab-backup create"
  tar_path="$(backup_tars | head -1)"
  [ -n "$tar_path" ] || die "backup finished but no tar found in /var/opt/gitlab/backups"
  ok "backup created: $(basename "$tar_path")"
  log "copy it out:  docker cp ${CONTAINER_NAME}:${tar_path} ."
  ;;
restore)
  # DESTRUCTIVE two-gate: overwrites the database + all repositories.
  src="${1:-}"
  [ $# -gt 0 ] && shift
  [ -n "$src" ] || usage_die "usage: aibox gitlab restore <backup.tar|latest> --yes"
  yes=0
  while [ $# -gt 0 ]; do
    case "$1" in
    --yes) yes=1 ;;
    *) usage_die "unknown option: $1" ;;
    esac
    shift
  done
  if [ "$yes" != 1 ]; then
    if [ -t 0 ] && [ -t 1 ]; then
      printf 'Overwrite the database and ALL repositories with %s? This cannot be undone. [y/N] ' "$src"
      read -r ans
      case "${ans:-}" in [yY]*) ;; *) usage_die "declined" ;; esac
    else
      usage_die "refusing without --yes (non-interactive): aibox gitlab restore $src --yes"
    fi
  fi
  # Argument validation BEFORE touching the deployment: a wrong path/name is a
  # usage error (2), not a runtime one, and must not depend on docker state.
  case "$src" in
  latest) ;;
  *)
    [ -f "$src" ] || usage_die "not found: $src"
    case "$(basename "$src")" in
    *_gitlab_backup.tar) ;;
    *) usage_die "not a GitLab backup tar (expected *_gitlab_backup.tar): $(basename "$src")" ;;
    esac
    ;;
  esac
  container_running || die_code 30 "container is not running (aibox gitlab start)"
  # secrets gate: a restore without the SOURCE secrets leaves encrypted
  # columns (CI variables, tokens, 2FA) unreadable, silently.
  if ! docker exec "$CONTAINER_NAME" test -s /etc/gitlab/gitlab-secrets.json 2>/dev/null; then
    warn "no /etc/gitlab/gitlab-secrets.json inside the container —"
    warn "restoring another instance's DB without its secrets breaks CI variables/tokens."
    warn "import them first: aibox gitlab import-secrets <source>/gitlab-secrets.json --yes"
  fi
  case "$src" in
  latest)
    tar_path="$(backup_tars | head -1)"
    [ -n "$tar_path" ] || die "no backup tar inside the container — pass a file path instead"
    bname="$(basename "$tar_path")"
    ;;
  *)
    bname="$(basename "$src")"
    log "copying ${bname} into the container…"
    docker cp "$src" "${CONTAINER_NAME}:/var/opt/gitlab/backups/${bname}"
    ;;
  esac
  backup_id="${bname%_gitlab_backup.tar}"
  before="$(db_count projects)"
  # Official restore procedure: stop puma + sidekiq first, restore, then bring
  # everything back up (same-version restore only — GitLab rejects a mismatch).
  log "restoring ${backup_id} (puma + sidekiq stopped first)…"
  docker exec "$CONTAINER_NAME" gitlab-ctl stop puma >/dev/null 2>&1 || true
  docker exec "$CONTAINER_NAME" gitlab-ctl stop sidekiq >/dev/null 2>&1 || true
  printf '%s\n' "yes" | docker exec -i -e BACKUP="$backup_id" "$CONTAINER_NAME" \
    gitlab-backup restore >/dev/null 2>&1 || \
    die "restore failed — run it by hand for details: docker exec -it $CONTAINER_NAME gitlab-backup restore BACKUP=$backup_id"
  log "restarting services and waiting for the web endpoint…"
  docker exec "$CONTAINER_NAME" gitlab-ctl restart >/dev/null 2>&1 || true
  waited=0
  until http_up || [ "$waited" -ge "${GITLAB_RESTORE_WAIT:-900}" ]; do sleep 10; waited=$((waited + 10)); done
  after="$(db_count projects)"
  if http_up; then
    ok "restore finished: projects ${before:-?} → ${after:-?}; web endpoint answering"
  else
    warn "restore finished: projects ${before:-?} → ${after:-?}; web endpoint not answering yet (first rails boot after a restore is slow — check: aibox gitlab logs)"
  fi
  log "repositories are in /var/opt/gitlab/git-data (gitlab_data volume); the volume must not be shared with another instance's data"
  ;;
import-secrets)
  # Two-gate: replaces the instance's secrets file (irreversible for encrypted data).
  sec="${1:-}"
  [ $# -gt 0 ] && shift
  [ -n "$sec" ] || usage_die "usage: aibox gitlab import-secrets <gitlab-secrets.json> --yes"
  [ -f "$sec" ] || usage_die "not found: $sec"
  yes=0
  while [ $# -gt 0 ]; do
    case "$1" in
    --yes) yes=1 ;;
    *) usage_die "unknown option: $1" ;;
    esac
    shift
  done
  if [ "$yes" != 1 ]; then
    if [ -t 0 ] && [ -t 1 ]; then
      printf 'Replace the container secrets with %s? [y/N] ' "$sec"
      read -r ans
      case "${ans:-}" in [yY]*) ;; *) usage_die "declined" ;; esac
    else
      usage_die "refusing without --yes (non-interactive): aibox gitlab import-secrets $sec --yes"
    fi
  fi
  container_running || die_code 30 "container is not running (aibox gitlab start)"
  docker cp "$sec" "${CONTAINER_NAME}:/etc/gitlab/gitlab-secrets.json"
  docker exec -u root "$CONTAINER_NAME" chown root:root /etc/gitlab/gitlab-secrets.json >/dev/null 2>&1 || true
  docker exec -u root "$CONTAINER_NAME" chmod 600 /etc/gitlab/gitlab-secrets.json >/dev/null 2>&1 || true
  ok "secrets imported from ${sec}"
  log "apply: aibox gitlab restart   (or: docker exec $CONTAINER_NAME gitlab-ctl reconfigure)"
  ;;
*)
  usage_die "unknown action: ${action:-} — run: aibox gitlab --help"
  ;;
esac
