# base module shared library (sourced by hooks, not executed directly)
# Shared PostgreSQL 18 + Redis 7: modules connect to the shared instance + use their own DB
# (<module> or <module>_<usage>).

export CLI_NAME="base"

# Deploy root (module-spec deploy-type convention).
base_deploy_root() {
  if [ -n "${BASE_DIR:-}" ]; then
    printf '%s' "${BASE_DIR}"
    return 0
  fi
  local b="${AIBOX_APPS_ROOT:-}"
  if [ -z "$b" ]; then
    b="${AIBOX_HOME:-${HOME:+${HOME}/.aibox}}/apps"
  fi
  printf '%s/base' "$b"
}

COMPOSE_FILE="$(base_deploy_root)/docker-compose.yml"
PG_HOST="127.0.0.1"
PG_PORT="${AIBOX_BASE_POSTGRES_PORT:-35432}"
PG_USER="${AIBOX_BASE_POSTGRES_USER:-aibox}"
PG_PASSWORD="${AIBOX_BASE_POSTGRES_PASSWORD:-aibox}"
REDIS_HOST="127.0.0.1"
REDIS_PORT="${AIBOX_BASE_REDIS_PORT:-36379}"
# Docker container/service names (consuming modules connect via this name; base.env's host is the same).
POSTGRES_CONTAINER="aibox-base-postgres"
REDIS_CONTAINER="aibox-base-redis"

# ---------- output / colors (TTY + NO_COLOR aware; no leakage into pipes) ----------
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  C_RST=$'\033[0m'; C_CYA=$'\033[36m'; C_YEL=$'\033[33m'; C_RED=$'\033[31m'
else
  C_RST=''; C_CYA=''; C_YEL=''; C_RED=''
fi

log() { printf '%s[base]%s %s\n' "$C_CYA" "$C_RST" "${*}"; }
warn() { printf '%s[!]%s %s\n' "$C_YEL" "$C_RST" "${*}" >&2; }
die() {
  printf '%s[x]%s %s\n' "$C_RED" "$C_RST" "${*}" >&2
  exit 1
}

# docker compose wrapper (selects the compose file with -f).
compose() {
  docker compose -f "$COMPOSE_FILE" "$@"
}

ensure_compose() {
  [ -f "$COMPOSE_FILE" ] || die "No compose file (first: aibox install base)"
}

# ---------- lifecycle ----------
# Writes $AIBOX_HOME/base.env — consuming modules inject it via compose --env-file (single source).
# Holds only instance-level shared info (host/port/user/password, from the container's perspective:
# service name + internal port); the DB name <module> is each module's own, not here.
write_base_env() {
  local env_file="${AIBOX_HOME}/base.env"
  mkdir -p "${AIBOX_HOME}"
  cat >"$env_file" <<EOF
# Generated by aibox base start — do not edit by hand; re-run base restart after changing base.
AIBOX_POSTGRES_HOST=${POSTGRES_CONTAINER}
AIBOX_POSTGRES_PORT=5432
AIBOX_POSTGRES_USER=${PG_USER}
AIBOX_POSTGRES_PASSWORD=${PG_PASSWORD}
AIBOX_REDIS_HOST=${REDIS_CONTAINER}
AIBOX_REDIS_PORT=6379
EOF
  log "Wrote ${env_file} (consumed by modules via compose --env-file)"
}

cmd_start() {
  ensure_compose
  log "Starting shared PG/Redis ..."
  compose up -d || die "Start failed (docker? see aibox base doctor)"
  write_base_env
  log "Shared PG/Redis started (PG ${PG_HOST}:${PG_PORT} / Redis ${REDIS_HOST}:${REDIS_PORT})"
  compose ps 2>/dev/null | sed 's/^/  /' || true
}

cmd_stop() {
  ensure_compose
  compose down
  log "Stopped (data volumes retained)"
}

cmd_status() {
  ensure_compose
  compose ps
  log "PG: ${PG_HOST}:${PG_PORT} (user=${PG_USER})  Redis: ${REDIS_HOST}:${REDIS_PORT}"
}

# ---------- createdb <module> [usage] ----------
# Create a module's DB on the shared PG: <module> or <module>_<usage> (prefix=module name, avoids cross-module clashes).
cmd_createdb() {
  local module="$1" usage="${2:-}" dbname
  if [ -n "$usage" ]; then
    dbname="${module}_${usage}"
  else
    dbname="$module"
  fi
  ensure_compose
  # Idempotent: skip if it already exists.
  if docker exec "$POSTGRES_CONTAINER" psql -U "$PG_USER" -tAc "SELECT 1 FROM pg_database WHERE datname='${dbname}'" 2>/dev/null | grep -q 1; then
    log "Database ${dbname} already exists (shared PG ${PG_HOST}:${PG_PORT})"
    return 0
  fi
  docker exec "$POSTGRES_CONTAINER" psql -U "$PG_USER" -c "CREATE DATABASE \"${dbname}\";" >/dev/null 2>&1 ||
    die "Creating database ${dbname} failed (PG not running? aibox base start)"
  log "Database ${dbname} ready (shared PG ${PG_HOST}:${PG_PORT})"
}

# ---------- Dashboard interface ----------
dashboard_info() {
  echo "endpoint=pg://${PG_HOST}:${PG_PORT} (user=${PG_USER}) + redis://${REDIS_HOST}:${REDIS_PORT}"
  echo "credential=PG user/password ${PG_USER}/* (override via AIBOX_BASE_POSTGRES_PASSWORD; consuming modules see ${AIBOX_HOME}/base.env)"
  echo "health=docker exec ${POSTGRES_CONTAINER} pg_isready -U ${PG_USER}"
}
